"""prompt global unique index

Revision ID: 8fa16f835bee
Revises: 95d60b928089
Create Date: 2026-08-05 16:16:13.042314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa16f835bee'
down_revision: Union[str, None] = '95d60b928089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_prompt_key_global', 'prompt_templates', ['key'], unique=True, postgresql_where=sa.text('site_id IS NULL'), sqlite_where=sa.text('site_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_prompt_key_global', table_name='prompt_templates', postgresql_where=sa.text('site_id IS NULL'), sqlite_where=sa.text('site_id IS NULL'))
    # ### end Alembic commands ###
