"""sites

Revision ID: b35e6e5c8ac7
Revises: b343354d02b0
Create Date: 2026-08-05 13:30:19.175895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35e6e5c8ac7'
down_revision: Union[str, None] = 'b343354d02b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('api_token_enc', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('site_description', sa.Text(), nullable=False),
    sa.Column('tone_of_voice', sa.Text(), nullable=False),
    sa.Column('publish_target', sa.String(length=20), nullable=False),
    sa.Column('articles_parent_id', sa.Integer(), nullable=True),
    sa.Column('articles_url_prefix', sa.String(length=200), nullable=False),
    sa.Column('reference_article_id', sa.Integer(), nullable=True),
    sa.Column('reference_html', sa.Text(), nullable=False),
    sa.Column('reference_images', sa.Integer(), nullable=False),
    sa.Column('reference_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_style_prompt', sa.Text(), nullable=False),
    sa.Column('cover_mode', sa.String(length=20), nullable=False),
    sa.Column('cover_style_prompt', sa.Text(), nullable=False),
    sa.Column('watermark_path', sa.String(length=400), nullable=False),
    sa.Column('builder_template_html', sa.Text(), nullable=False),
    sa.Column('builder_parent_id', sa.Integer(), nullable=True),
    sa.Column('teaser_category_id', sa.Integer(), nullable=True),
    sa.Column('teaser_city_id', sa.Integer(), nullable=True),
    sa.Column('teaser_location_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    # ### end Alembic commands ###
